In [85]:
#!pip install ucimlrepo

In [86]:

# data (as pandas dataframes) 
# X = predict_students_dropout_and_academic_success.data.features 
# y = predict_students_dropout_and_academic_success.data.targets 



In [87]:
import pandas as pd 
df = pd.read_csv('files/playground-series-s4e6/train.csv')



In [88]:
# Exibir todas as linhas
pd.set_option('display.max_rows', None)

# Exibir todas as colunas
pd.set_option('display.max_columns', None)

In [89]:
df.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           126.0            1                       1   
1                           125.0            1                      19   
2                           137.0            1                       3   
3                           131.0            1                      19   
4                           132.0            1                      19   

   Father's qualification  Mother's occupation  Father's occupation  \
0                      19                    5                    5   
1                      19                    9                    9   
2                      19                    2                    3   
3                       3                    3                    2   
4                      37                    4                    9   

   Admission grade  Displaced  Educational special needs  Debtor  \
0            122.6          0                          0       0   
1            119.8          1                          0       0   
2            144.7          0                          0       0   
3            126.1          1                          0       0   
4            120.1          1                          0       0   

   Tuition fees up to date  Gender  Scholarship holder  Age at enrollment  \
0                        1       0                   1                 18   
1                        1       0                   0                 18   
2                        1       1                   0                 18   
3                        1       0                   1                 18   
4                        1       0                   0                 18   

   International  Curricular units 1st sem (credited)  \
0              0                                    0   
1              0                                    0   
2              0                                    0   
3              0                                    0   
4              0                                    0   

   Curricular units 1st sem (enrolled)  \
0                                    6   
1                                    6   
2                                    6   
3                                    7   
4                                    7   

   Curricular units 1st sem (evaluations)  \
0                                       6   
1                                       8   
2                                       0   
3                                       9   
4                                      12   

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    6                         14.500000   
1                                    4                         11.600000   
2                                    0                          0.000000   
3                                    7                         12.591250   
4                                    6                         12.933333   

   Curricular units 1st sem (without evaluations)  \
0                                               0   
1                                               0   
2           

In [90]:
categorical_features = ['Marital status' ,'Application mode' ,'Application order' ,'Course'
                        ,'Previous qualification', "Mother's qualification", "Father's qualification" ]
colums = [ 'Marital status' ,'Application mode' ,'Application order' ,'Course'
        ,'Previous qualification' , 'Debtor',
        'Tuition fees up to date', 'Gender', 'Scholarship holder',
        'Age at enrollment', 'International','Inflation rate', 'GDP', 'Target',
        "Mother's qualification", "Father's qualification",'Displaced',
        'Educational special needs', 'Debtor']
df = df[colums]

In [91]:

#categorical_features = df.drop('Target',axis=1).columns
for var in categorical_features:
    cat_list = pd.get_dummies(df[var], prefix=var)
    data1=df.join(cat_list)
    df=data1
    df.drop(var, axis=1, inplace=True)

df.head()


Debtor  Tuition fees up to date  Gender  Scholarship holder  \
0       0                        1       0                   1   
1       0                        1       0                   0   
2       0                        1       1                   0   
3       0                        1       0                   1   
4       0                        1       0                   0   

   Age at enrollment  International  Inflation rate   GDP    Target  \
0                 18              0             0.6  2.02  Graduate   
1                 18              0             0.6  2.02   Dropout   
2                 18              0             0.3 -0.92   Dropout   
3                 18              0             0.6  2.02  Enrolled   
4                 18              0             2.6  0.32  Graduate   

   Displaced  Educational special needs  Debtor  Marital status_1  \
0          0                          0       0              True   
1          1                          0       0              True   
2          0                          0       0              True   
3          1                          0       0              True   
4          1                          0       0              True   

   Marital status_2  Marital status_3  Marital status_4  Marital status_5  \
0             False             False             False             False   
1             False             False             False             False   
2             False             False             False             False   
3             False             False             False             False   
4             False             False             False             False   

   Marital status_6  Application mode_1  Application mode_2  \
0             False                True               False   
1             False               False               False   
2             False               False               False   
3             False                True               False   
4             False                True               False   

   Application mode_3  Application mode_4  Application mode_5  \
0               False               False               False   
1               False               False               False   
2               False               False               False   
3               False               False               False   
4               False               False               False   

   Application mode_7  Application mode_9  Application mode_10  \
0               False               False                False   
1               False               False                False   
2               False               False                False   
3               False               False                False   
4               False               False                False   

   Application mode_12  Application mode_15  Application mode_16  \
0                False                False                False   
1                False                False                False   
2                False                False                False   
3                False                False                False   
4                False                False                False   

   Application mode_17  Application mode_18  Application mode_26  \
0                False                False                False   
1                 True                False                False   
2                 True                False                False   
3                False                False                False   
4                False                False                False   

   Application mode_27  Application mode_35  Application mode_39  \
0                False                False                False   
1                False                False                False   
2                False                False                False   
3                False                False 

In [92]:

X = df.drop('Target', axis=1)
y = df[['Target']]

  
# metadata 
print(predict_students_dropout_and_academic_success.metadata) 
  
# variable information 
print(predict_students_dropout_and_academic_success.variables) 

# variable information 
print(predict_students_dropout_and_academic_success.variables) 

# variable information 
print(predict_students_dropout_and_academic_success.variables) 

In [93]:
# Criar um dicionário de mapeamento
target_map = {
    'Graduate': 1,
    'Dropout': 2,
    'Enrolled': 3
}

y['Target'] = y['Target'].map(target_map)

/var/folders/1j/ptwbwzc11rq1nwvd4_x252n80000gn/T/ipykernel_80583/3817780791.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Target'] = y['Target'].map(target_map)


In [94]:
y['Target'].unique()

array([1, 2, 3])

In [95]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report




In [96]:
# Divisão do dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [97]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.fit_transform(X_test)

In [98]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [99]:
# Treinamento do modelo
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=42)

In [100]:
# Predição e avaliação
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5769  776  714]
 [ 976 3528  524]
 [1327  784  906]]
              precision    recall  f1-score   support

           1       0.71      0.79      0.75      7259
           2       0.69      0.70      0.70      5028
           3       0.42      0.30      0.35      3017

    accuracy                           0.67     15304
   macro avg       0.61      0.60      0.60     15304
weighted avg       0.65      0.67      0.66     15304



In [101]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.svm import SVC
from sklearn.svm import LinearSVC, NuSVC, SVC

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, SGDClassifier
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier

In [102]:
models = {
    "SVC":SVC(gamma='auto'),
    "NuSVC":NuSVC(gamma='auto'),
    "LinearSVC":LinearSVC(),
    "SGDClassifier":SGDClassifier(max_iter=100, tol=1e-3),
    "KNeighborsClassifier":KNeighborsClassifier(),
    "LogisticRegression":LogisticRegression(solver='lbfgs'),
    "LogisticRegressionCV":LogisticRegressionCV(cv=3),
    "BaggingClassifier":BaggingClassifier(),
    "ExtraTreesClassifie":ExtraTreesClassifier(n_estimators=300),
    "RandomForestClassifier":RandomForestClassifier(n_estimators=300)
}

In [103]:
# Avaliação de Modelos

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    
    if "Classifier" in name or "Logistic" in name or "SVM" in name:
        accuracy = accuracy_score(y_test, predictions)
    else:
        accuracy = mean_squared_error(y_test, predictions)

    y_pred = predictions
    print(f'{name} - Acurácia: {accuracy}')
    print(classification_report(y_test, y_pred))    


/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC - Acurácia: 0.691257187663356
              precision    recall  f1-score   support

           1       0.70      0.86      0.77      7259
           2       0.73      0.68      0.70      5028
           3       0.49      0.30      0.37      3017

    accuracy                           0.69     15304
   macro avg       0.64      0.61      0.62     15304
weighted avg       0.67      0.69      0.67     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NuSVC - Acurácia: 0.7165446941975954
              precision    recall  f1-score   support

           1       0.69      0.85      0.76      7259
           2       0.73      0.66      0.69      5028
           3       0.50      0.29      0.36      3017

    accuracy                           0.68     15304
   macro avg       0.64      0.60      0.61     15304
weighted avg       0.66      0.68      0.66     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearSVC - Acurácia: 0.6868139048614741
              precision    recall  f1-score   support

           1       0.70      0.87      0.77      7259
           2       0.74      0.69      0.71      5028
           3       0.51      0.27      0.35      3017

    accuracy                           0.69     15304
   macro avg       0.65      0.61      0.61     15304
weighted avg       0.68      0.69      0.67     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier - Acurácia: 0.6778619968635651
              precision    recall  f1-score   support

           1       0.67      0.88      0.76      7259
           2       0.74      0.66      0.70      5028
           3       0.50      0.23      0.31      3017

    accuracy                           0.68     15304
   macro avg       0.64      0.59      0.59     15304
weighted avg       0.66      0.68      0.65     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier - Acurácia: 0.6454521693674856
              precision    recall  f1-score   support

           1       0.67      0.82      0.74      7259
           2       0.69      0.63      0.65      5028
           3       0.42      0.25      0.31      3017

    accuracy                           0.65     15304
   macro avg       0.59      0.57      0.57     15304
weighted avg       0.63      0.65      0.63     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression - Acurácia: 0.6943936225823314
              precision    recall  f1-score   support

           1       0.71      0.86      0.78      7259
           2       0.74      0.69      0.71      5028
           3       0.50      0.31      0.38      3017

    accuracy                           0.69     15304
   macro avg       0.65      0.62      0.63     15304
weighted avg       0.68      0.69      0.68     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegressionCV - Acurácia: 0.6936748562467329
              precision    recall  f1-score   support

           1       0.71      0.86      0.78      7259
           2       0.74      0.69      0.71      5028
           3       0.50      0.31      0.38      3017

    accuracy                           0.69     15304
   macro avg       0.65      0.62      0.62     15304
weighted avg       0.68      0.69      0.68     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/ensemble/_bagging.py:888: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier - Acurácia: 0.6429038159958181
              precision    recall  f1-score   support

           1       0.70      0.77      0.73      7259
           2       0.67      0.67      0.67      5028
           3       0.39      0.30      0.34      3017

    accuracy                           0.64     15304
   macro avg       0.59      0.58      0.58     15304
weighted avg       0.63      0.64      0.63     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ExtraTreesClassifie - Acurácia: 0.7637872451646628
              precision    recall  f1-score   support

           1       0.71      0.77      0.74      7259
           2       0.68      0.68      0.68      5028
           3       0.39      0.30      0.34      3017

    accuracy                           0.65     15304
   macro avg       0.59      0.59      0.59     15304
weighted avg       0.64      0.65      0.64     15304



/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier - Acurácia: 0.6664924202822792
              precision    recall  f1-score   support

           1       0.71      0.80      0.75      7259
           2       0.69      0.70      0.69      5028
           3       0.43      0.30      0.35      3017

    accuracy                           0.67     15304
   macro avg       0.61      0.60      0.60     15304
weighted avg       0.65      0.67      0.65     15304



In [104]:
y_pred

array([1, 2, 1, ..., 1, 1, 1])

In [106]:
# Ajuste de hiperparâmetros (opcional)
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.feature_selection import RFE
'''
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, interaction_only=True)),
    ('feature_selection', RFE(estimator=LogisticRegression(), n_features_to_select=10)),
    ('classifier', LogisticRegression(solver='liblinear'))
])

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, interaction_only=True)),
    ('feature_selection', RFE(estimator=SVC(), n_features_to_select=10)),
    ('classifier', SVC(gamma='auto'))
])

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, interaction_only=True)),
    ('feature_selection', RFE(estimator=SVC(), n_features_to_select=10)),
    ('classifier', SVC(gamma='auto'))
])
'''
pipeline = Pipeline([
    ('scaler', StandardScaler()),  # You can add more preprocessing steps if needed
    ('clf', ExtraTreesClassifier(n_estimators=300, random_state=42))
])

# Definir grid de parâmetros
'''
param_grid = {
    'classifier__C': [0.01, 0.1, 1, 10, 100],
    'classifier__penalty': ['l1', 'l2']
}
'''
param_grid = {
    'clf__n_estimators': [50, 100, 200],
    'clf__max_depth': [None, 10, 20, 30],
    'clf__min_samples_split': [2, 5, 10],
    'clf__min_samples_leaf': [1, 2, 4],
    'clf__max_features': ['auto', 'sqrt', 'log2'],
    'clf__bootstrap': [False, True],
    'clf__criterion': ['gini', 'entropy']
}

# Grid search
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)




/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py:1018: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(self.var_), copy=False, constant_mask=constant_mask
/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py:1018: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(self.var_), copy=False, constant_mask=constant_mask
/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py:1018: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(self.var_), copy=False, constant_mask=constant_mask
/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py:1018: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(self.var_), copy=False, constant_mask=constant_mask
/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_data.py:1018: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(self.var_), copy=False, constant_mask=constant_mask
/opt/homebrew/lib/python3.11/site-packag

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('clf',
                                        ExtraTreesClassifier(n_estimators=300,
                                                             random_state=42))]),
             n_jobs=-1,
             param_grid={'clf__bootstrap': [False, True],
                         'clf__criterion': ['gini', 'entropy'],
                         'clf__max_depth': [None, 10, 20, 30],
                         'clf__max_features': ['auto', 'sqrt', 'log2'],
                         'clf__min_samples_leaf': [1, 2, 4],
                         'clf__min_samples_split': [2, 5, 10],
                         'clf__n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [107]:
grid_search.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf',
                 ExtraTreesClassifier(criterion='entropy', min_samples_leaf=2,
                                      min_samples_split=10, random_state=42))])

In [108]:
model = grid_search.best_estimator_
model.fit(X_train, y_train)

# Avaliação
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[[6244  663  352]
 [1058 3583  387]
 [1471  751  795]]
              precision    recall  f1-score   support

           1       0.71      0.86      0.78      7259
           2       0.72      0.71      0.71      5028
           3       0.52      0.26      0.35      3017

    accuracy                           0.69     15304
   macro avg       0.65      0.61      0.61     15304
weighted avg       0.68      0.69      0.67     15304

